name: antrophia-ui

proxy:
  node:
    # expose and route traffic to port 8080 for vue webpack-dev-server
    - antrophia.lndo.site:8080
    - storybook-antrophia.lndo.site:6006

services:
  appserver:
    type: nginx:1.14
    ssl: true
    webroot: dist
    overrides:
      ports: ['8888:80']
  node:
    type: node:11
    globals:
      "@vue/cli": latest
      "@vue/cli-service-global": latest
      yarn: latest
    build:
      - yarn install
    command: yarn serve

tooling:
  npm:
    service: node
  node:
    service: node
  vue:
    service: node
  yarn:
    service: node
