# Lando Docs: https://docs.devwithlando.io/
name: antrophia-ui

# Proxy Docs: https://docs.devwithlando.io/config/proxy.html
proxy:
  appserver:
    - antrophia.lndo.site
  node:
    - node.antrophia.lndo.site

# Services Docs: https://docs.devwithlando.io/config/services.html
services:
  appserver:
    type: nginx:1.14
    ssl: true
    webroot: dist

  node:
    type: node:11
    globals:
      "@vue/cli": "^3.5.1"
    build:
      - yarn install

# Tooling Docs: https://docs.devwithlando.io/config/tooling.html
tooling:
  # Expose `lando npm`
  npm:
    service: node
  # Expose `lando node`
  node:
    service: node
  # Expose `lando vue`
  vue:
    service: node
  # Expose `lando yarn`
  yarn:
    service: node
